# Generated by Django 6.0.1 on 2026-01-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livro_co_autor_alter_livro_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
